package view;

import controller.ProjectController;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Project;

/**
 *
 * @author decio
 */
public class DialogProjectScreen extends javax.swing.JDialog {

    ProjectController controller;
    
    public DialogProjectScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        controller = new ProjectController();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelProjectScreen = new javax.swing.JPanel();
        toolbarProjectScreen = new javax.swing.JPanel();
        labelProjectScreen = new javax.swing.JLabel();
        saveProject = new javax.swing.JLabel();
        panel2ProjectScreen = new javax.swing.JPanel();
        labelProjectName = new javax.swing.JLabel();
        labelProjectDescription = new javax.swing.JLabel();
        textFieldProjectName = new javax.swing.JTextField();
        scrollPanelProjectDescription = new javax.swing.JScrollPane();
        textFieldProjectDescription = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 550));

        panelProjectScreen.setBackground(new java.awt.Color(155, 8, 0));

        toolbarProjectScreen.setBackground(new java.awt.Color(155, 8, 0));

        labelProjectScreen.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelProjectScreen.setForeground(new java.awt.Color(255, 255, 255));
        labelProjectScreen.setText("Projeto");

        saveProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check(3).png"))); // NOI18N
        saveProject.setToolTipText("Salvar");
        saveProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveProjectMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout toolbarProjectScreenLayout = new javax.swing.GroupLayout(toolbarProjectScreen);
        toolbarProjectScreen.setLayout(toolbarProjectScreenLayout);
        toolbarProjectScreenLayout.setHorizontalGroup(
            toolbarProjectScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolbarProjectScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelProjectScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(saveProject, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        toolbarProjectScreenLayout.setVerticalGroup(
            toolbarProjectScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolbarProjectScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(toolbarProjectScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(saveProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelProjectScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panel2ProjectScreen.setBackground(new java.awt.Color(204, 204, 204));

        labelProjectName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelProjectName.setForeground(new java.awt.Color(29, 36, 64));
        labelProjectName.setText("Nome");

        labelProjectDescription.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelProjectDescription.setForeground(new java.awt.Color(29, 36, 64));
        labelProjectDescription.setText("Descrição");

        textFieldProjectName.setBackground(new java.awt.Color(255, 255, 255));
        textFieldProjectName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFieldProjectName.setForeground(new java.awt.Color(29, 36, 64));
        textFieldProjectName.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(102, 102, 102)));

        textFieldProjectDescription.setBackground(new java.awt.Color(255, 255, 255));
        textFieldProjectDescription.setColumns(20);
        textFieldProjectDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFieldProjectDescription.setForeground(new java.awt.Color(29, 36, 64));
        textFieldProjectDescription.setRows(5);
        textFieldProjectDescription.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(102, 102, 102)));
        scrollPanelProjectDescription.setViewportView(textFieldProjectDescription);

        javax.swing.GroupLayout panel2ProjectScreenLayout = new javax.swing.GroupLayout(panel2ProjectScreen);
        panel2ProjectScreen.setLayout(panel2ProjectScreenLayout);
        panel2ProjectScreenLayout.setHorizontalGroup(
            panel2ProjectScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2ProjectScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2ProjectScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPanelProjectDescription)
                    .addComponent(labelProjectName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelProjectDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldProjectName, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        panel2ProjectScreenLayout.setVerticalGroup(
            panel2ProjectScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2ProjectScreenLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(labelProjectName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelProjectDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanelProjectDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelProjectScreenLayout = new javax.swing.GroupLayout(panelProjectScreen);
        panelProjectScreen.setLayout(panelProjectScreenLayout);
        panelProjectScreenLayout.setHorizontalGroup(
            panelProjectScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbarProjectScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelProjectScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel2ProjectScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelProjectScreenLayout.setVerticalGroup(
            panelProjectScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProjectScreenLayout.createSequentialGroup()
                .addComponent(toolbarProjectScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel2ProjectScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelProjectScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelProjectScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveProjectMouseClicked
        Project project = new Project();
        
        try {
            if (!textFieldProjectName.getText().equals("")) {
                project.setName(textFieldProjectName.getText());
                project.setDescription(textFieldProjectDescription.getText());
                project.setCreateAt(new Date());
                project.setUpdateAt(new Date());
                controller.save(project);
                JOptionPane.showMessageDialog(rootPane, "Projeto salvo com sucesso!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "O projeto não fois alvo pois o campo nome não foi preenchido!");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_saveProjectMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogProjectScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogProjectScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogProjectScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogProjectScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogProjectScreen dialog = new DialogProjectScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelProjectDescription;
    private javax.swing.JLabel labelProjectName;
    private javax.swing.JLabel labelProjectScreen;
    private javax.swing.JPanel panel2ProjectScreen;
    private javax.swing.JPanel panelProjectScreen;
    private javax.swing.JLabel saveProject;
    private javax.swing.JScrollPane scrollPanelProjectDescription;
    private javax.swing.JTextArea textFieldProjectDescription;
    private javax.swing.JTextField textFieldProjectName;
    private javax.swing.JPanel toolbarProjectScreen;
    // End of variables declaration//GEN-END:variables
}
